// Copyright 2022 mjohns
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
#define LOCKING_SUPPORT_ENABLE

/* Locking resynchronize hack */
#define LOCKING_RESYNC_ENABLE

/* Enables This makes it easier for fast typists to use dual-function keys */
#define PERMISSIVE_HOLD

/* mouse config */
#define MOUSEKEY_DELAY          0
// Lowering MOUSEKEY_INTERVAL raises the cursor speed significantly, you may want to lower MOUSEKEY_MAX_SPEED (default: 10)
#define MOUSEKEY_INTERVAL       20
#define MOUSEKEY_MAX_SPEED       7
#define MOUSEKEY_WHEEL_DELAY 0

/* layer config */
#define TAPPING_TOGGLE 1

/* QMK_SETTINGS is on, so Vial keeps its own copy in EEPROM and these are only
 * the defaults it starts from. */

/* Identifies the board to vial.rocks. Generated by
 * util/vial_generate_keyboard_uid.py; must stay unique to this keyboard. */
#define VIAL_KEYBOARD_UID {0x3B, 0x58, 0x1C, 0x39, 0x43, 0xD5, 0x8A, 0xF4}

/* Hold both outer top corner keys to let Vial write to the keyboard. */
#define VIAL_UNLOCK_COMBO_ROWS {0, 6}
#define VIAL_UNLOCK_COMBO_COLS {0, 5}

/* 3 * MATRIX_ROWS * MATRIX_COLS * 2 = 432 bytes of the 1 KB EEPROM, the rest
 * being macro buffer. A fourth layer would cost 144 more, and a reflash. */
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
