meta:
  engine: 4.1.0
points:
  zones:
    matrix:
      columns:
        outer:
        pinky:
        ring:
          # key.splay: -5
          # key.origin: [-12, -19]
          key.stagger: 5
        middle:
          key.stagger: 2
        index:
          key.stagger: -2
        inner:
          key.stagger: -2
      rows:
        mod:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-28, -40]
      columns:
        near:
        home:
          key.spread: 21.25
          key.splay: -15
          # key.origin: [-11.75, -9]
        far:
          key.spread: 21.25
          key.splay: -15
          # key.origin: [-9.5, -9]
      rows:
        thumb:
  mirror:
    ref: matrix_pinky_home
    distance: 250

outlines:
  left:
    - where: true
      what: rectangle
      size: [cx + 2, cy + 2]
      fillet: 1
  leftkeys:
    - where: true
      what: rectangle
      size: [14, 14]
  leftcutout:
    - name: left
    - operation: subtract
      name: leftkeys

pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      keyswitches:
        where: true
        what: mx
        params:
          hotswap: true
          from: '{{col_net}}'
          to: '{{colrow}}'

cases:
  plate:
    - name: leftcutout
      extrude: 1.2
