meta:
  engine: 4.1.0
points:
  zones:
    matrix:
      columns:
        outer:
        pinky:
        ring:
          key.stagger: 5
        middle:
          key.stagger: 2
        index:
          key.stagger: -2
        inner:
          key.stagger: -2
      rows:
        mod:
        bottom:
        home:
        top:
      anchor:
        # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
        shift: [100, -150]

    thumbfan:
      anchor:
        ref: matrix_index_mod
        shift: [-0.5u, -1u]
      columns:
        near:
        home:
          key.spread: 21.25
          key.splay: -15
          key.stagger: -2
        far:
          key:
            height: 1.5u
            splay: -15
            shift: [2, 3.5]
      rows:
        thumb:
  mirror:
    ref: matrix_pinky_home
    distance: 250

outlines:
  switchplate:
    - what: polygon
      operation: stack
      fillet: 0
      points:
        - ref: matrix_outer_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_outer_mod
          shift: [-0.5u, -0.5u]
        - ref: matrix_middle_mod
          shift: [-0.5u, -1u + 2]
        - ref: thumbfan_near_thumb
          shift: [-0.5u, -0.5u]
        - ref: thumbfan_far_thumb
          shift: [-0.5u + 1.5, -0.8u]

        - ref: thumbfan_far_thumb
          shift: [0.5u, -0.8u]
        - ref: thumbfan_far_thumb
          shift: [0.5u, 0.8u]

        - ref: matrix_inner_mod
          shift: [0.5u, -0.08u]
        - ref: matrix_inner_top
          shift: [0.5u, 0.5u]
        - ref: matrix_inner_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_index_top
          shift: [0.5u, 0.5u]
        - ref: matrix_index_top
          shift: [-0.5u, 0.5u]
        - ref: matrix_index_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_middle_top
          shift: [0.5u, 0.5u]
        - ref: matrix_middle_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_ring_top
          shift: [0.5u, 0.5u]
        - ref: matrix_ring_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_pinky_top
          shift: [0.5u, 0.5u]

  pcb:
    - what: polygon
      operation: stack
      fillet: 0
      points:
        - ref: matrix_outer_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_outer_mod
          shift: [-0.5u, -0.5u]
        - ref: matrix_middle_mod
          shift: [-0.5u, -1u + 2]
        - ref: thumbfan_near_thumb
          shift: [-0.5u, -0.5u]
        - ref: thumbfan_far_thumb
          shift: [-0.5u + 1.5, -0.8u]

        - ref: thumbfan_far_thumb
          shift: [0.5u, -0.8u]
        - ref: thumbfan_far_thumb
          shift: [0.5u, 0.8u]

        # right top corner
        - ref: matrix_inner_top
          shift: [1.5u + 2, 0.5u -2]

        - ref: matrix_inner_top
          shift: [0.5u, 0.5u -2]
        - ref: matrix_inner_top
          shift: [0.5u, 0.5u]

        - ref: matrix_inner_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_inner_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_index_top
          shift: [0.5u, 0.5u]
        - ref: matrix_index_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_middle_top
          shift: [0.5u, 0.5u]
        - ref: matrix_middle_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_ring_top
          shift: [0.5u, 0.5u]
        - ref: matrix_ring_top
          shift: [-0.5u, 0.5u]

        - ref: matrix_pinky_top
          shift: [0.5u, 0.5u]
  left:
    - where: true
      what: rectangle
      size: [cx + 2, cy + 2]
      fillet: 2
  leftkeys:
    - where: true
      what: rectangle
      size: [14, 14]
  leftcutout:
    - name: left
    - operation: subtract
      name: leftkeys
  test:
    - name: leftkeys
    - operation: stack
      name: pcb

pcbs:
  left:
    outlines:
      main:
        outline: pcb
    footprints:
      keyswitches:
        where: true
        what: mx
        params:
          hotswap: true
          from: '{{col_net}}'
          to: '{{colrow}}'
      # Main diodes
      diode_main:
        what: diode
        where: true
        params:
          from: '{{colrow}}'
          to: '{{row_net}}'
        adjust:
          shift: [0, -4.5]
          rotate: 0
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [20, -12]
          rotate: -90.0
      nice_view:
        what: nice_view
        params:
          SDA: P0.17
          SCL: P0.20
          CS: P0.24
        # orientation: up
        where:
          ref: matrix_inner_top
          shift: [20, -30]
          rotate: 90.0
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_bottom
          shift: [23, 4]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [0.5u + 19, 2.8]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [0.5u + 19, -6.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW

cases:
  plate:
    - name: leftcutout
      extrude: 1.2
